spring:
  application:
    name: springboot
  jackson:
    property-naming-strategy: SNAKE_CASE
  # flyway:
  #   locations: classpath:/db/migration
  #   schemas: employees
  #   baselineOnMigrate: true
  #   enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_ARGS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
  address: 0.0.0.0
